[package]
name = "bench-parser"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
oxc_parser = "0.3.0"
oxc_allocator = "0.3.0"
oxc_span = "0.3.0"
swc_ecma_parser = "0.141.24"
swc_ecma_ast = "0.110.10"
rome_js_parser = "0.0.2"
rome_js_syntax = "0.0.2"

num_cpus = "1.16.0"
criterion = { version = "0.5" }
rayon = "1.8.0"
mimalloc = "0.1.39"
codspeed-criterion-compat = { version = "2.3.2", default-features = false, optional = true }

[features]
codspeed = ["codspeed-criterion-compat"]

[[bench]]
name = "parser"
harness = false

[profile.release]
opt-level     = 3
lto           = "fat"
codegen-units = 1
strip         = "symbols"
debug         = false
panic         = "abort"
